name: Docker Image CI

on:
  push:
    branches: [ master, feature/mock-test ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.registry_user_name }}
        password: ${{ secrets.registry_user_password }}
        registry: registry.cn-beijing.aliyuncs.com
        repository: pointstone/mirrors.cug.edu.cn-web
        tag_with_sha: true
